<?php 
return [
    'id'             => 'mobile_settings',
    'title'          => 'Mobile',
    'panel'          => 'header_panel',
    'priority'      => 35,
    'fields'         => [
        [
            'name' => esc_attr__( 'Mobile items - Top', 'architronix' ),
            'id'   => 'mobile_items_top',
            'type' => 'select',
            'clone' => true,
            'sort_clone' => true,
            'max_clone' => 3,
            'add_button' => '+',
            'std' => ['mobile-tagline'],
            'options' => [
                'mobile-tagline' => 'Mobile Tagline',
                'phone' => 'Phone',
                'email' => 'Email', 
                'social_icons' => 'Social links',
                'buttons' => 'Buttons',
                'cart' => 'Cart',
                'search' => 'Search',                
            ],
        ],
        [
            'name' => esc_attr__( 'Mobile items - Bottom', 'architronix' ),
            'id'   => 'mobile_items_bottom',
            'type' => 'select',
            'clone' => true,
            'sort_clone' => true,
            'max_clone' => 3,
            'add_button' => '+',
            'std' => ['phone', 'social_icons'],
            'options' => [
                'mobile-tagline' => 'Mobile Tagline',
                'phone' => 'Phone',
                'email' => 'Email', 
                'social_icons' => 'Social links',
                'buttons' => 'Buttons',
                'cart' => 'Cart',
                'search' => 'Search',
            ],
        ],
        [
            'name' => esc_attr__('Mobile Header Tagline', 'architronix'),
            'id' => 'mobile_header_tagline',
            'type' => 'textarea',
            'std' => '[site_title] - [site_tagline]',
            'desc' => sprintf(esc_attr__( 'Use %s for %s, %s for %s','architronix' ), '<code>[site_title]</code>', '<strong>Site Title</strong>', '<code>[site_tagline]</code>', '<strong>Site Tagline</strong>'),
        ],
    ],
];
