<?php
return [
    'id'             => 'topbar_settings',
    'title'          => 'Topbar',
    'panel'          => 'header_panel',
    'priority'      => 1,
    'fields'         => [
        [
            'name' => esc_attr__( 'Topbar items - Left', 'architronix' ),
            'id'   => 'topbar_items_left',
            'type' => 'select',
            'clone' => true,
            'sort_clone' => true,
            'max_clone' => 2,
            'add_button' => '+',
            'std' => ['tagline'],
            'options' => [
                'tagline' => 'Tagline',
                'phone' => 'Phone',
                'email' => 'Email', 
                'social_icons' => 'Social links',
                'buttons' => 'Buttons',
                'cart' => 'Cart',
                'search' => 'Search',                
            ],
        ],
        [
            'name' => esc_attr__( 'Topbar items - Right', 'architronix' ),
            'id'   => 'topbar_items_right',
            'type' => 'select',
            'clone' => true,
            'sort_clone' => true,
            'max_clone' => 2,
            'add_button' => '+',
            'std' => ['phone', 'social_icons'],
            'options' => [
                'tagline' => 'Tagline',
                'phone' => 'Phone',
                'email' => 'Email', 
                'social_icons' => 'Social links',
                'buttons' => 'Buttons',
                'cart' => 'Cart',
                'search' => 'Search',
            ],
        ],
        [
            'name' => esc_attr__('Header Tagline', 'architronix'),
            'id' => 'header_tagline',
            'type' => 'textarea',
            'std' => '[site_title] - [site_tagline]',
            'desc' => sprintf(esc_attr__( 'Use %s for %s, %s for %s','architronix' ), '<code>[site_title]</code>', '<strong>Site Title</strong>', '<code>[site_tagline]</code>', '<strong>Site Tagline</strong>'),
        ],
    ],
];