<?php 
return [
    'title'           => esc_attr__('About Section', 'architronix'),
    'id'              => 'about-us',
    'icon'            => 'clipboard',
    'description'     => 'Give a quick, clear snapshot of your company to the visitors',    
    'fields'          => [
        [
            'name'            => 'About Section Style',
            'id'              => 'template_file',
            'type'            => 'select',
            'std'             => 'blocks/about-us-1.php',
            'options'         => [
                'blocks/about-us-1.php'       => 'Style 1',
                'blocks/about-us-2.php'       => 'Style 2',
                'blocks/about-us-3.php'       => 'Style 3',
            ],
        ],
        [
            'id'               => 'image',
            'name'             => esc_attr__('Image',  'architronix'),
            'desc'             => esc_attr__('This image will be displayed on the left side of the services list', 'architronix'),
            'type'             => 'single_image', 
            'force_delete'     => false,
            'max_file_uploads' => 1,
            'max_status'       => false,
            'image_size'       => 'architronix-584x823-cropped',
            'std'              => ''
        ],
        [
            'name'        => esc_attr__('Title', 'architronix'),
            'id'          => 'title',
            'desc'        => esc_attr__('Type your section title here', 'architronix'),
            'type'        => 'text',
            'std'        => esc_attr__('Designing Dreams: Our Story', 'architronix'),
            'placeholder' => esc_attr__('Title', 'architronix'),   
            'visible'          => ['template_file', 'in', ['blocks/about-us-2.php', 'blocks/about-us-3.php'] ],   
        ],
        [
            'name'        => esc_attr__('Short Description', 'architronix'),
            'id'          => 'short_desc',
            'desc'        => esc_attr__('Write short description for the section', 'architronix'),
            'type'        => 'textarea',
            'std'        => esc_attr__('At Architronix, design is our canvas, and spaces are our masterpieces. With a vision for elegance, functionality, and innovation, our creative team curates environments that reflect dreams. From chic urban apartments to countryside estates, we\'re committed to sustainable design practices that enrich lives and the planet.', 'architronix'),
            'placeholder' => esc_attr__('Short Description', 'architronix'), 
            'visible'          => ['template_file', '=', 'blocks/about-us-2.php'],          
        ], 
        [   
            'name'              => esc_attr__('Services List', 'architronix'),
            'id'                => 'services',
            'type'              => 'group', 
            'clone'             => true,
            'clone_default'     => true,
            'clone_as_multiple' => true,
            'collapsible'       => true,
            'default_state'     => 'collapsed',
            'group_title'       => '{#}. {service_title}',
            'max_clone'         => 10,
            'add_button'        => __( 'Add More', 'architronix' ),
            'visible'          => ['template_file', 'in',['blocks/about-us-1.php', 'blocks/about-us-3.php']],  
            'std'               => [
                [
                    'service_count' => '01',
                    'service_title' => 'Innovation Beyond Boundaries',
                    'service_desc' => 'We thrive on challenging the norms, infusing each project with fresh, innovative perspectives that defy convention.',
                ],
                [
                    'service_count' => '02',
                    'service_title' => 'Visionaries at Work',
                    'service_desc' => 'We\'re not just designers; we\'re dream weavers. Your visions become our blueprints for extraordinary spaces.',
                ],
                [
                    'service_count' => '03',
                    'service_title' => 'Awards and Acclaim',
                    'service_desc' => 'Join us on a journey marked by accolades and distinctions as we carve our path in the world of design.',
                ],              
            ],
            'fields'            => [
                [
                    'name'        => esc_attr__('Serial No.', 'architronix'),
                    'id'          => 'service_count',
                    'desc'        => esc_attr__('Type Service Serial Number', 'architronix'),
                    'type'        => 'text',
                    'placeholder' => esc_attr__('Serial No.',   'architronix'),                      
                ],
                [
                    'name'        => esc_attr__('Title', 'architronix'),
                    'id'          => 'service_title',
                    'desc'        => esc_attr__('Type Service\'s Title', 'architronix'),
                    'type'        => 'text',
                    'placeholder' => esc_attr__('Service Title',   'architronix'),                  
                ],
                [
                    'name'        => esc_attr__('Short Description', 'architronix'),
                    'id'          => 'service_desc',
                    'desc'        => esc_attr__('Write service\'s short description', 'architronix'),
                    'type'        => 'textarea',
                    'placeholder' => esc_attr__('Short Description',   'architronix'),                        
                ],
            ],
        ],
        [
            'name'        => esc_attr__('Button Text', 'architronix'),
            'id'          => 'button_text',
            'desc'        => esc_attr__('Edit Button Text', 'architronix'),
            'type'        => 'text',
            'std'         => 'Learn more About Us',
            'placeholder' => esc_attr__('Learn more About Us', 'architronix'),
            'visible'          => ['template_file', '=', 'blocks/about-us-1.php' ],  
        ],
         
        [
            'name'        => esc_attr__('Button URL', 'architronix'),
            'id'          => 'button_url',
            'desc'        => esc_attr__('URL for the button', 'architronix'),
            'type'        => 'text',
            'std'         => '#',
            'placeholder' => esc_attr__('Enter button URL here', 'architronix'), 
            'visible'          => ['template_file', '=', 'blocks/about-us-1.php' ],     
        ],
        [
            'name'        => esc_attr__('Add Custom Class', 'architronix'),
            'id'          => 'additional_class',
            'desc'        => esc_attr__('Type Custom Class', 'architronix'),
            'type'        => 'text',
            'std'         => '',     
        ],
                  
    ],
];