<?php
return [
    'title'           => esc_attr__('Map', 'architronix'),
    'id'              => 'map-field',
    'icon'            => 'admin-site-alt',
    'description'     => 'Select Map Locations to show on map',
    'fields'          => [
        [
            'name'            => 'Map Style',
            'id'              => 'template',
            'type'            => 'hidden',
            'std'             => 'blocks/map-field.php',
        ],
        [
            'name'              => esc_attr__('Locations', 'architronix'),
            'id'                => 'locations',
            'type'              => 'group',
            'clone'             => true,
            'clone_default'     => true,
            'clone_as_multiple' => true,
            'collapsible'       => true,
            'default_state'     => 'collapsed',
            'group_title'       => '{#}. {company_name}',
            'max_clone'         => 10,
            'add_button'        => __('Add new locations', 'architronix'),
            'std'               => [
                [
                    'location_sl'    => '01',
                    'location_map_title' => 'Architronix USA',
                    'company_name'   => 'Architronix Inc.',
                    'address'        => '208 English Road, High Point, NC 27262, USA',
                    'latitude'       => '39.80442819377875',
                    'longitude'      => '-101.75829822449703',               
                ],
                [
                    'location_sl'    => '02',
                    'location_map_title' => 'Architronix Spain',
                    'company_name'   => 'Architronix',
                    'address'        => 'Avda. Valencia, 3, 46891, Palomar (Valencia), SPAIN',
                    'latitude'       => '40.36932496262613',
                    'longitude'      => '-3.656264074036898',
                ],
                [
                    'location_sl'    => '03',
                    'location_map_title' => 'Architronix London',
                    'company_name'   => 'Architronix LTD',
                    'address'        => 'Avda. Valencia, 3, 46891, London, England',
                    'latitude'       => '51.5073337282129',
                    'longitude'      => '-0.1491657174319576',
                ],
            ],

            'fields'            => [
                [
                    'name'        => esc_attr__('Serial', 'architronix'),
                    'id'          => 'location_sl',
                    'desc'        => esc_attr__('Location serial number', 'architronix'),
                    'type'        => 'text',
                    'placeholder' => esc_attr__('Serial',   'architronix'),
                ],
                [
                    'name'        => esc_attr__('Map Title', 'architronix'),
                    'id'          => 'location_map_title',
                    'desc'        => esc_attr__('Name your map title', 'architronix'),
                    'type'        => 'text',
                    'placeholder' => esc_attr__('Title',   'architronix'),
                ],
                [
                    'name'        => esc_attr__('Company Name', 'architronix'),
                    'id'          => 'company_name',
                    'desc'        => esc_attr__('Type Company Name', 'architronix'),
                    'type'        => 'text',
                    'placeholder' => esc_attr__('Company Name',   'architronix'),
                ],
                [
                    'name'        => esc_attr__('Address', 'architronix'),
                    'id'          => 'address',
                    'desc'        => esc_attr__('Type Full Address', 'architronix'),
                    'type'        => 'text',
                    'placeholder' => esc_attr__('Address',   'architronix'),
                ],
                [
                    'name'        => esc_attr__('Latitude', 'architronix'),
                    'id'          => 'latitude',
                    'desc'        => esc_attr__('Type Latitude', 'architronix'),
                    'type'        => 'text',
                    'placeholder' => esc_attr__('Latitude',   'architronix'),
                ],
                [
                    'name'        => esc_attr__('Longitude', 'architronix'),
                    'id'          => 'longitude',
                    'desc'        => esc_attr__('Type longitude', 'architronix'),
                    'type'        => 'text',
                    'placeholder' => esc_attr__('longitude',   'architronix'),
                ],
                [
                    'name'              => esc_attr__('Add Contacts', 'architronix'),
                    'id'                => 'contacts',
                    'type'              => 'group',
                    'clone'             => true,
                    'clone_default'     => true,
                    'clone_as_multiple' => true,
                    'collapsible'       => true,
                    'default_state'     => 'collapsed',
                    'group_title'       => '{#}. {contact_label}',
                    'max_clone'         => 10,
                    'add_button'        => __('Add Contact', 'architronix'),
                    'std'               => [               
                            [
                                'contact_label'    => 'Phone:',
                                'contact_info'     => '336 885 6670'
                            ],    
                    ],
                    'fields' => [
                        [
                            'name'        => esc_attr__('Label', 'architronix'),
                            'id'          => 'contact_label',
                            'desc'        => esc_attr__('Type Contact Label', 'architronix'),
                            'type'        => 'text',
                            'placeholder' => esc_attr__('Label',   'architronix'),
                        ],
                        [
                            'name'        => esc_attr__('Info', 'architronix'),
                            'id'          => 'contact_info',
                            'desc'        => esc_attr__('Type Contact Information', 'architronix'),
                            'type'        => 'text',
                            'placeholder' => esc_attr__('Info',   'architronix'),
                        ],         
                    ],
                ],
            ],
        ],
    ],
];