<?php
return [
    'title'           => esc_attr__('Map Section', 'architronix'),
    'id'              => 'map',
    'icon'            => 'admin-site-alt',
    'description'     => 'Select your map style',
    'fields'          => [
        [
            'name'            => 'Map Style',
            'id'              => 'template',
            'type'            => 'select',
            'std'             => 'blocks/map-section-1.php',
            'options'         => [
                'blocks/map-section-1.php'       => 'Map Style 1',
                'blocks/map-section-2.php'       => 'Map Style 2',
            ],
        ],
        [
            'name'              => esc_attr__('Locations', 'architronix'),
            'id'                => 'locations',
            'type'              => 'group',
            'clone'             => true,
            'clone_default'     => true,
            'clone_as_multiple' => true,
            'collapsible'       => true,
            'default_state'     => 'collapsed',
            'group_title'       => '{#}. {company_name}',
            'max_clone'         => 10,
            'add_button'        => __('Add new locations', 'architronix'),
            'std'               => [
                [
                    'location_sl'    => '01',
                    'location_title' => 'Address USA:',
                    'company_name'   => 'Architronix Inc.',
                    'address'        => '208 English Road, High Point, NC 27262, USA',
                    'location_map_title' => 'Architronix USA',
                    'latitude'       => '39.80442819377875',
                    'longitude'      => '-101.75829822449703',
                    
                ],
                [
                    'location_sl'    => '02',
                    'location_title' => 'Address Spain:',
                    'company_name'   => 'Architronix',
                    'address'        => 'Avda. Valencia, 3, 46891, Palomar (Valencia), SPAIN',
                    'location_map_title' => 'Architronix Spain',
                    'latitude'       => '40.36932496262613',
                    'longitude'      => '-3.656264074036898',
                ],
                [
                    'location_sl'    => '03',
                    'location_title' => 'Address London:',
                    'company_name'   => 'Architronix LTD',
                    'address'        => 'Avda. Valencia, 3, 46891, London, England',
                    'location_map_title' => 'Architronix London',
                    'latitude'       => '51.5073337282129',
                    'longitude'      => '-0.1491657174319576',
                ],
            ],
            'fields'            => [
                [
                    'name'        => esc_attr__('Serial', 'architronix'),
                    'id'          => 'location_sl',
                    'desc'        => esc_attr__('Location serial number', 'architronix'),
                    'type'        => 'text',
                    'placeholder' => esc_attr__('Serial',   'architronix'),
                ],
                [
                    'name'        => esc_attr__('Title', 'architronix'),
                    'id'          => 'location_title',
                    'desc'        => esc_attr__('Name your location title', 'architronix'),
                    'type'        => 'text',
                    'placeholder' => esc_attr__('Title',   'architronix'),
                ],
                [
                    'name'        => esc_attr__('Company Name', 'architronix'),
                    'id'          => 'company_name',
                    'desc'        => esc_attr__('Type Company Name', 'architronix'),
                    'type'        => 'text',
                    'placeholder' => esc_attr__('Company Name',   'architronix'),
                ],
                [
                    'name'        => esc_attr__('Address', 'architronix'),
                    'id'          => 'address',
                    'desc'        => esc_attr__('Type Full Address', 'architronix'),
                    'type'        => 'text',
                    'placeholder' => esc_attr__('Address',   'architronix'),
                ],
                [
                    'name'        => esc_attr__('Map Title', 'architronix'),
                    'id'          => 'location_map_title',
                    'desc'        => esc_attr__('Name your map title', 'architronix'),
                    'type'        => 'text',
                    'placeholder' => esc_attr__('Title', 'architronix'),
                ],
                [
                    'name'        => esc_attr__('Latitude', 'architronix'),
                    'id'          => 'latitude',
                    'desc'        => esc_attr__('Type Latitude', 'architronix'),
                    'type'        => 'text',
                    'placeholder' => esc_attr__('Latitude', 'architronix'),
                ],
                [
                    'name'        => esc_attr__('Longitude', 'architronix'),
                    'id'          => 'longitude',
                    'desc'        => esc_attr__('Type longitude', 'architronix'),
                    'type'        => 'text',
                    'placeholder' => esc_attr__('longitude', 'architronix'),
                ],
                [
                    'name'        => esc_attr__('Phone', 'architronix'),
                    'id'          => 'contact_phone',
                    'desc'        => esc_attr__('Type Phone Number', 'architronix'),
                    'type'        => 'text',
                    'placeholder' => esc_attr__('Contact No.', 'architronix'),
                    'std'         => esc_attr__('+34 96 239 84 86', 'architronix'),
                ],
                [
                    'name'        => esc_attr__('Email', 'architronix'),
                    'id'          => 'contact_email',
                    'desc'        => esc_attr__('Type Your Email', 'architronix'),
                    'type'        => 'text',
                    'placeholder' => esc_attr__('hello@architronix.com', 'architronix'),
                    'std'         => esc_attr__('hello@architronix.com', 'architronix'), 
                ],         
            ],
        ],
        [
            'name'        => esc_attr__('Add Custom Class', 'architronix'),
            'id'          => 'additional_class',
            'desc'        => esc_attr__('Type Custom Class', 'architronix'),
            'type'        => 'text',
            'std'         => '',     
        ],
    ],
];